---
abstract: 'An interface to the SendGrid email service'
author:
  - 'Jonathan Lloyd <webmaster@lifegames.org>'
build_requires:
  Data::Dumper: 0
  Test::More: 0.96
  Try::Tiny: 0.09
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-SendGrid
requires:
  Carp: 0
  DateTime::Format::Mail: 0
  HTTP::Request: 0
  HTTP::Response: 0
  JSON::XS: 2.3
  Moose: 2
  Moose::Util::TypeConstraints: 2
  MooseX::Method::Signatures: 0.36
  URI: 0
version: 1.0
